import type { Product } from "@/types";

/**
 * ============================================================================
 * DEMO PRODUCT CATALOG — REPLACE WITH REAL INVENTORY
 * ============================================================================
 * Every product below is a DEMO/PLACEHOLDER (isDemo: true) with a local SVG
 * placeholder image (see /public/images/products, generated by
 * /scripts/generate-placeholders.py). None of this represents real stock,
 * real prices, or a real prescription-dispensing workflow.
 *
 * TO ADD / EDIT / REMOVE A PRODUCT: edit the `products` array below. Each
 * entry follows the `Product` type defined in /types/index.ts:
 *   id, name, slug, brand, category, description, price, salePrice, image,
 *   stock, sku, featured, prescriptionRequired, createdAt, isDemo
 *
 * `slug` powers the URL at /products/[slug] — keep it lowercase, hyphenated,
 * and unique. `category` must match a `slug` in /data/categories.ts. `image`
 * can point to any local file under /public or a remote URL (add the host to
 * next.config.js -> images.remotePatterns first).
 *
 * WHEN YOU CONNECT A REAL DATABASE (PostgreSQL/Supabase):
 * This array is designed to map 1:1 onto a `products` table with the same
 * column names. Replace the functions below (getAllProducts, getProductBySlug,
 * etc.) with real queries — every page already imports products through
 * these helper functions rather than importing the array directly, so the
 * swap only touches this one file.
 * ============================================================================
 */

export const products: Product[] = [
  {
    id: 1,
    name: "Panadol 500mg (20 Tablets)",
    slug: "panadol-500mg",
    brand: "GSK",
    category: "medicines",
    description:
      "Fast-acting paracetamol tablets for the relief of mild to moderate pain and fever, including headaches, toothache, and cold & flu symptoms.",
    keyInfo: [
      "Active ingredient: Paracetamol 500mg",
      "Pack size: 20 tablets",
      "For adults and children over 12 years",
      "Store below 25°C in a dry place",
    ],
    price: 250,
    salePrice: 220,
    image: "/images/products/panadol-500mg.svg",
    stock: 50,
    sku: "MED-PAN-500",
    featured: true,
    prescriptionRequired: false,
    createdAt: "2026-06-01",
    isDemo: true,
  },
  {
    id: 2,
    name: "Augmentin 625mg (10 Tablets)",
    slug: "augmentin-625mg",
    brand: "GSK",
    category: "medicines",
    description:
      "Broad-spectrum antibiotic combining amoxicillin and clavulanic acid, used to treat a range of bacterial infections.",
    keyInfo: [
      "Active ingredient: Amoxicillin 500mg + Clavulanic acid 125mg",
      "Pack size: 10 tablets",
      "Prescription required by law",
    ],
    price: 850,
    image: "/images/products/augmentin-625mg.svg",
    stock: 30,
    sku: "MED-AUG-625",
    featured: false,
    prescriptionRequired: true,
    createdAt: "2026-05-20",
    isDemo: true,
  },
  {
    id: 3,
    name: "Brufen 400mg (30 Tablets)",
    slug: "brufen-400mg",
    brand: "Abbott",
    category: "medicines",
    description:
      "Ibuprofen tablets for relief of pain, inflammation, and fever including muscular aches, backache, and period pain.",
    keyInfo: [
      "Active ingredient: Ibuprofen 400mg",
      "Pack size: 30 tablets",
      "Take with food or milk",
    ],
    price: 180,
    image: "/images/products/brufen-400mg.svg",
    stock: 40,
    sku: "MED-BRU-400",
    featured: false,
    prescriptionRequired: false,
    createdAt: "2026-04-15",
    isDemo: true,
  },
  {
    id: 4,
    name: "Flagyl 400mg (14 Tablets)",
    slug: "flagyl-400mg",
    brand: "Sanofi",
    category: "medicines",
    description:
      "Metronidazole antibiotic tablets used to treat certain bacterial and parasitic infections.",
    keyInfo: [
      "Active ingredient: Metronidazole 400mg",
      "Pack size: 14 tablets",
      "Prescription required by law",
    ],
    price: 210,
    image: "/images/products/flagyl-400mg.svg",
    stock: 25,
    sku: "MED-FLA-400",
    featured: false,
    prescriptionRequired: true,
    createdAt: "2026-03-10",
    isDemo: true,
  },
  {
    id: 5,
    name: "ORS Rehydration Sachets (Pack of 10)",
    slug: "ors-rehydration-sachets",
    brand: "Pharmatec",
    category: "medicines",
    description:
      "Oral rehydration salts to help restore fluids and electrolytes lost during diarrhea, vomiting, or dehydration.",
    keyInfo: [
      "Pack size: 10 sachets",
      "Dissolve in 200ml clean water",
      "Suitable for adults and children",
    ],
    price: 40,
    image: "/images/products/ors-rehydration-sachets.svg",
    stock: 100,
    sku: "MED-ORS-010",
    featured: true,
    prescriptionRequired: false,
    createdAt: "2026-07-02",
    isDemo: true,
  },
  {
    id: 6,
    name: "Centrum Multivitamin (30 Tablets)",
    slug: "centrum-multivitamin-30",
    brand: "Pfizer",
    category: "vitamins-supplements",
    description:
      "A complete daily multivitamin with minerals to support energy, immunity, and overall wellbeing.",
    keyInfo: [
      "One tablet daily with food",
      "Pack size: 30 tablets",
      "Contains 24 vitamins and minerals",
    ],
    price: 1450,
    salePrice: 1300,
    image: "/images/products/centrum-multivitamin-30.svg",
    stock: 20,
    sku: "VIT-CEN-030",
    featured: true,
    prescriptionRequired: false,
    createdAt: "2026-06-18",
    isDemo: true,
  },
  {
    id: 7,
    name: "Vitamin C 1000mg Effervescent (20 Tabs)",
    slug: "vitamin-c-1000mg-effervescent",
    brand: "Herbion",
    category: "vitamins-supplements",
    description:
      "Effervescent vitamin C tablets to support immune health, dissolve in water for a refreshing daily dose.",
    keyInfo: [
      "Pack size: 20 effervescent tablets",
      "Dissolve in a glass of water",
      "Orange flavor",
    ],
    price: 650,
    image: "/images/products/vitamin-c-1000mg-effervescent.svg",
    stock: 35,
    sku: "VIT-VTC-020",
    featured: false,
    prescriptionRequired: false,
    createdAt: "2026-05-05",
    isDemo: true,
  },
  {
    id: 8,
    name: "Calcium + Vitamin D3 Tablets (60 Tabs)",
    slug: "calcium-vitamin-d3-tablets",
    brand: "GSK",
    category: "vitamins-supplements",
    description:
      "Calcium and vitamin D3 supplement to support strong bones and teeth.",
    keyInfo: [
      "Pack size: 60 tablets",
      "One tablet twice daily",
      "Suitable for adults",
    ],
    price: 780,
    image: "/images/products/calcium-vitamin-d3-tablets.svg",
    stock: 0,
    sku: "VIT-CAD-060",
    featured: false,
    prescriptionRequired: false,
    createdAt: "2026-02-14",
    isDemo: true,
  },
  {
    id: 9,
    name: "Omega-3 Fish Oil Capsules (60 Softgels)",
    slug: "omega-3-fish-oil-capsules",
    brand: "Nature's Bounty",
    category: "vitamins-supplements",
    description:
      "Fish oil softgels rich in Omega-3 fatty acids (EPA & DHA) to support heart and brain health.",
    keyInfo: [
      "Pack size: 60 softgels",
      "One softgel daily with a meal",
      "1000mg fish oil per capsule",
    ],
    price: 1900,
    image: "/images/products/omega-3-fish-oil-capsules.svg",
    stock: 15,
    sku: "VIT-OMG-060",
    featured: false,
    prescriptionRequired: false,
    createdAt: "2026-01-28",
    isDemo: true,
  },
  {
    id: 10,
    name: "Dettol Antiseptic Liquid 250ml",
    slug: "dettol-antiseptic-liquid-250ml",
    brand: "Reckitt",
    category: "personal-care",
    description:
      "Trusted antiseptic disinfectant liquid for first aid, household cleaning, and personal hygiene.",
    keyInfo: [
      "Size: 250ml",
      "Dilute before use as directed",
      "Kills 99.9% of germs",
    ],
    price: 320,
    image: "/images/products/dettol-antiseptic-liquid-250ml.svg",
    stock: 60,
    sku: "PC-DET-250",
    featured: true,
    prescriptionRequired: false,
    createdAt: "2026-06-25",
    isDemo: true,
  },
  {
    id: 11,
    name: "Sensodyne Toothpaste 100g",
    slug: "sensodyne-toothpaste-100g",
    brand: "GSK",
    category: "personal-care",
    description:
      "Toothpaste formulated for sensitive teeth, providing lasting sensitivity relief with regular brushing.",
    keyInfo: ["Size: 100g", "Use twice daily", "Fluoride toothpaste"],
    price: 380,
    salePrice: 340,
    image: "/images/products/sensodyne-toothpaste-100g.svg",
    stock: 45,
    sku: "PC-SEN-100",
    featured: false,
    prescriptionRequired: false,
    createdAt: "2026-04-30",
    isDemo: true,
  },
  {
    id: 12,
    name: "Hand Sanitizer 500ml (Pump Bottle)",
    slug: "hand-sanitizer-500ml",
    brand: "Safeguard",
    category: "personal-care",
    description:
      "Alcohol-based hand sanitizer that kills germs without water, ideal for home, office, or on the go.",
    keyInfo: ["Size: 500ml", "70% alcohol content", "Pump dispenser bottle"],
    price: 250,
    image: "/images/products/hand-sanitizer-500ml.svg",
    stock: 80,
    sku: "PC-SAN-500",
    featured: false,
    prescriptionRequired: false,
    createdAt: "2026-03-22",
    isDemo: true,
  },
  {
    id: 13,
    name: "Johnson's Baby Shampoo 200ml",
    slug: "johnsons-baby-shampoo-200ml",
    brand: "Johnson & Johnson",
    category: "baby-care",
    description:
      "Gentle, tear-free formula baby shampoo that cleanses softly while caring for delicate hair and scalp.",
    keyInfo: ["Size: 200ml", "No More Tears formula", "Dermatologist tested"],
    price: 480,
    image: "/images/products/johnsons-baby-shampoo-200ml.svg",
    stock: 30,
    sku: "BC-JBS-200",
    featured: true,
    prescriptionRequired: false,
    createdAt: "2026-06-10",
    isDemo: true,
  },
  {
    id: 14,
    name: "Pampers Diapers Size 3 (20 pcs)",
    slug: "pampers-diapers-size-3",
    brand: "Pampers",
    category: "baby-care",
    description:
      "Soft and absorbent diapers that keep babies dry and comfortable for up to 12 hours.",
    keyInfo: [
      "Pack size: 20 diapers",
      "Size 3 (6–10 kg)",
      "Up to 12 hours protection",
    ],
    price: 1250,
    salePrice: 1100,
    image: "/images/products/pampers-diapers-size-3.svg",
    stock: 25,
    sku: "BC-PAM-S3",
    featured: false,
    prescriptionRequired: false,
    createdAt: "2026-05-12",
    isDemo: true,
  },
  {
    id: 15,
    name: "Cetaphil Gentle Skin Cleanser 250ml",
    slug: "cetaphil-gentle-skin-cleanser",
    brand: "Galderma",
    category: "beauty-skincare",
    description:
      "A soap-free, non-irritating cleanser suitable for sensitive skin, dermatologist recommended.",
    keyInfo: ["Size: 250ml", "Soap-free formula", "Suitable for sensitive skin"],
    price: 1650,
    image: "/images/products/cetaphil-gentle-skin-cleanser.svg",
    stock: 18,
    sku: "BS-CET-250",
    featured: true,
    prescriptionRequired: false,
    createdAt: "2026-07-08",
    isDemo: true,
  },
  {
    id: 16,
    name: "Nivea Body Lotion 400ml",
    slug: "nivea-body-lotion-400ml",
    brand: "Nivea",
    category: "beauty-skincare",
    description:
      "Nourishing body lotion that absorbs quickly, leaving skin soft and smooth for 24 hours.",
    keyInfo: ["Size: 400ml", "24-hour moisture", "For all skin types"],
    price: 890,
    image: "/images/products/nivea-body-lotion-400ml.svg",
    stock: 40,
    sku: "BS-NIV-400",
    featured: false,
    prescriptionRequired: false,
    createdAt: "2026-02-27",
    isDemo: true,
  },
  {
    id: 17,
    name: "Digital Blood Pressure Monitor",
    slug: "digital-blood-pressure-monitor",
    brand: "Omron",
    category: "medical-devices",
    description:
      "Automatic upper-arm blood pressure monitor with large digital display for easy at-home monitoring.",
    keyInfo: [
      "Automatic upper-arm cuff",
      "Stores up to 60 readings",
      "Includes batteries",
    ],
    price: 4500,
    image: "/images/products/digital-blood-pressure-monitor.svg",
    stock: 12,
    sku: "MD-OMR-BPM",
    featured: true,
    prescriptionRequired: false,
    createdAt: "2026-06-30",
    isDemo: true,
  },
  {
    id: 18,
    name: "Infrared Digital Thermometer",
    slug: "infrared-digital-thermometer",
    brand: "Beurer",
    category: "medical-devices",
    description:
      "Non-contact infrared thermometer for fast and accurate temperature readings, ideal for the whole family.",
    keyInfo: [
      "Non-contact measurement",
      "1-second reading",
      "Fever alarm indicator",
    ],
    price: 2200,
    salePrice: 1950,
    image: "/images/products/infrared-digital-thermometer.svg",
    stock: 22,
    sku: "MD-BEU-THM",
    featured: false,
    prescriptionRequired: false,
    createdAt: "2026-04-02",
    isDemo: true,
  },
  {
    id: 19,
    name: "Family First Aid Kit",
    slug: "family-first-aid-kit",
    brand: "MedPlus",
    category: "first-aid",
    description:
      "A comprehensive first aid kit for the home, stocked with bandages, antiseptic wipes, and basic supplies.",
    keyInfo: [
      "40+ pieces included",
      "Compact carry case",
      "Suitable for home or travel",
    ],
    price: 1500,
    image: "/images/products/family-first-aid-kit.svg",
    stock: 20,
    sku: "FA-KIT-FAM",
    featured: false,
    prescriptionRequired: false,
    createdAt: "2026-03-15",
    isDemo: true,
  },
  {
    id: 20,
    name: "Adhesive Bandages Box (100 pcs)",
    slug: "adhesive-bandages-box-100",
    brand: "MedPlus",
    category: "first-aid",
    description:
      "Assorted sizes of breathable adhesive bandages for minor cuts and scrapes.",
    keyInfo: ["100 assorted bandages", "Breathable fabric strips", "Latex-free"],
    price: 150,
    image: "/images/products/adhesive-bandages-box-100.svg",
    stock: 70,
    sku: "FA-BND-100",
    featured: false,
    prescriptionRequired: false,
    createdAt: "2026-01-10",
    isDemo: true,
  },
  {
    id: 21,
    name: "Herbal Immunity Green Tea (25 Bags)",
    slug: "herbal-immunity-green-tea",
    brand: "Tapal",
    category: "health-wellness",
    description:
      "A soothing herbal green tea blend to support daily wellness as part of a balanced lifestyle.",
    keyInfo: ["Pack size: 25 tea bags", "Caffeine-light blend", "Steep 3-5 minutes"],
    price: 550,
    image: "/images/products/herbal-immunity-green-tea.svg",
    stock: 33,
    sku: "HW-GTE-025",
    featured: true,
    prescriptionRequired: false,
    createdAt: "2026-07-15",
    isDemo: true,
  },
];

// ---------------------------------------------------------------------------
// Data-access helpers. Every page/component should go through these
// functions rather than importing `products` directly, so a future swap to
// PostgreSQL/Supabase only requires changing the implementations below.
// ---------------------------------------------------------------------------

export function getAllProducts(): Product[] {
  return products;
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, limit);
}

export function searchProducts(query: string): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q)
  );
}
